/**
 * TypeScript bridge to the canonical PostgreSQL runtime database module.
 *
 * The previous TypeScript migration stub used SQLite. Keeping this file as a
 * thin bridge prevents stale TS imports from drifting away from `database.js`,
 * which is the production PostgreSQL implementation used by `server.js`.
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const db: Record<string, any> = require('../database');

export type Row = Record<string, any>;

export interface QueueRequest extends Row {
    id: string;
    client_id?: string | null;
    client_name: string;
    language: string;
    target_phone?: string | null;
    room_name: string;
    position: number;
    status?: string;
    created_at?: string | Date;
}

export const initialize = db.initialize;
export const getAdminByUsername = db.getAdminByUsername;
export const createAdmin = db.createAdmin;
export const getAllInterpreters = db.getAllInterpreters;
export const getInterpreter = db.getInterpreter;
export const getInterpreterByEmail = db.getInterpreterByEmail;
export const createInterpreter = db.createInterpreter;
export const updateInterpreter = db.updateInterpreter;
export const deleteInterpreter = db.deleteInterpreter;
export const getInterpreterStats = db.getInterpreterStats;
export const getAllCaptioners = db.getAllCaptioners;
export const getCaptioner = db.getCaptioner;
export const getCaptionerByEmail = db.getCaptionerByEmail;
export const createCaptioner = db.createCaptioner;
export const updateCaptioner = db.updateCaptioner;
export const deleteCaptioner = db.deleteCaptioner;
export const getAllClients = db.getAllClients;
export const getClient = db.getClient;
export const getClientByEmail = db.getClientByEmail;
export const createClient = db.createClient;
export const updateClient = db.updateClient;
export const createCall = db.createCall as (call: Row) => Promise<string>;
export const endCall = db.endCall;
export const getCall = db.getCall;
export const getActiveCalls = db.getActiveCalls;
export const addToQueue = db.addToQueue as (request: Row) => Promise<{ id: string; position: number }>;
export const getQueueRequests = db.getQueueRequests as (status?: string) => Promise<QueueRequest[]>;
export const assignInterpreter = db.assignInterpreter as (requestId: string, interpreterId: string) => Promise<void>;
export const assignInterpreterToRequest = db.assignInterpreter as (requestId: string, interpreterId: string) => Promise<void>;
export const completeRequest = db.completeRequest;
export const removeFromQueue = db.removeFromQueue;
export const reorderQueue = db.reorderQueue;
export const logActivity = db.logActivity;
export const getActivityLog = db.getActivityLog;
export const getDashboardStats = db.getDashboardStats;
export const getDailyUsageStats = db.getDailyUsageStats;
export const getSpeedDialEntries = db.getSpeedDialEntries;
export const addSpeedDialEntry = db.addSpeedDialEntry;
export const updateSpeedDialEntry = db.updateSpeedDialEntry;
export const deleteSpeedDialEntry = db.deleteSpeedDialEntry;
export const incrementSpeedDialUsage = db.incrementSpeedDialUsage;
export const getClientPhoneNumbers = db.getClientPhoneNumbers;
export const assignClientPhoneNumber = db.assignClientPhoneNumber;
export const getInterpreterShifts = db.getInterpreterShifts;
export const createInterpreterShift = db.createInterpreterShift;
export const updateInterpreterShift = db.updateInterpreterShift;
export const getInterpreterEarnings = db.getInterpreterEarnings;
export const getClientCallHistory = db.getClientCallHistory;
export const getInterpreterCallHistory = db.getInterpreterCallHistory;
export const getClientByPhoneNumber = db.getClientByPhoneNumber;
export const createP2PCall = db.createP2PCall;
export const createMissedCall = db.createMissedCall;
export const getMissedCalls = db.getMissedCalls;
export const markMissedCallsSeen = db.markMissedCallsSeen;
export const getActiveP2PRoomsForClient = db.getActiveP2PRoomsForClient;
export const getContacts = db.getContacts;
export const getContact = db.getContact;
export const createContact = db.createContact;
export const updateContact = db.updateContact;
export const deleteContact = db.deleteContact;
export const getContactGroups = db.getContactGroups;
export const createContactGroup = db.createContactGroup;
export const updateContactGroup = db.updateContactGroup;
export const deleteContactGroup = db.deleteContactGroup;
export const setContactGroups = db.setContactGroups;
export const getBlockedContacts = db.getBlockedContacts;
export const blockContact = db.blockContact;
export const unblockContact = db.unblockContact;
export const isContactBlocked = db.isContactBlocked;
export const findDuplicateContacts = db.findDuplicateContacts;
export const mergeContacts = db.mergeContacts;
export const importContacts = db.importContacts;
export const migrateSpeedDialToContacts = db.migrateSpeedDialToContacts;
export const ensureDefaultGroups = db.ensureDefaultGroups;
export const getContactCallHistory = db.getContactCallHistory;
export const getContactNotes = db.getContactNotes;
export const createContactNote = db.createContactNote;
export const updateContactNote = db.updateContactNote;
export const deleteContactNote = db.deleteContactNote;
export const getContactTimeline = db.getContactTimeline;
export const logContactChange = db.logContactChange;
export const getContactChangesSince = db.getContactChangesSince;
export const getGoogleOAuthToken = db.getGoogleOAuthToken;
export const upsertGoogleOAuthToken = db.upsertGoogleOAuthToken;
export const deleteGoogleOAuthToken = db.deleteGoogleOAuthToken;
export const getClientPreferences = db.getClientPreferences;
export const updateClientPreferences = db.updateClientPreferences;
export const isClientDND = db.isClientDND;
export const getAllActiveSessions = db.getAllActiveSessions;
export const upsertActiveSession = db.upsertActiveSession;
export const deleteActiveSession = db.deleteActiveSession;
export const getAllActiveHandoffTokens = db.getAllActiveHandoffTokens;
export const storeHandoffToken = db.storeHandoffToken;
export const deleteHandoffToken = db.deleteHandoffToken;
export const deleteHandoffTokensByUser = db.deleteHandoffTokensByUser;
export const deleteExpiredHandoffTokens = db.deleteExpiredHandoffTokens;
export const createCallTransfer = db.createCallTransfer;
export const updateCallTransferStatus = db.updateCallTransferStatus;
export const getCallTransfers = db.getCallTransfers;
export const getPendingTransferForCall = db.getPendingTransferForCall;
export const addConferenceParticipant = db.addConferenceParticipant;
export const removeConferenceParticipant = db.removeConferenceParticipant;
export const getConferenceParticipants = db.getConferenceParticipants;
export const addChatMessage = db.addChatMessage;
export const getChatMessages = db.getChatMessages;
export const setCallOnHold = db.setCallOnHold;
export const getActiveCallForClient = db.getActiveCallForClient;
export const getTtsSettings = db.getTtsSettings;
export const updateTtsSettings = db.updateTtsSettings;
export const getQuickPhrases = db.getQuickPhrases;
export const addQuickPhrase = db.addQuickPhrase;
export const updateQuickPhrase = db.updateQuickPhrase;
export const deleteQuickPhrase = db.deleteQuickPhrase;
export const createVCOCall = db.createVCOCall;
export const createOtpCode = db.createOtpCode;
export const verifyOtpCode = db.verifyOtpCode;
export const createPasswordReset = db.createPasswordReset;
export const consumePasswordReset = db.consumePasswordReset;
export const updateClientPassword = db.updateClientPassword;
export const updateInterpreterPassword = db.updateInterpreterPassword;
export const createVoicemailMessage = db.createVoicemailMessage;
export const getVoicemailMessage = db.getVoicemailMessage;
export const getVoicemailMessageByRoomName = db.getVoicemailMessageByRoomName;
export const updateVoicemailMessage = db.updateVoicemailMessage;
export const deleteVoicemailMessage = db.deleteVoicemailMessage;
export const getVoicemailInbox = db.getVoicemailInbox;
export const getVoicemailInboxCount = db.getVoicemailInboxCount;
export const getVoicemailUnreadCount = db.getVoicemailUnreadCount;
export const markVoicemailSeen = db.markVoicemailSeen;
export const getVoicemailStorageUsage = db.getVoicemailStorageUsage;
export const getVoicemailMessageCount = db.getVoicemailMessageCount;
export const getExpiredVoicemailMessages = db.getExpiredVoicemailMessages;
export const getActiveVoicemailRecordings = db.getActiveVoicemailRecordings;
export const getVoicemailSetting = db.getVoicemailSetting;
export const getAllVoicemailSettings = db.getAllVoicemailSettings;
export const setVoicemailSetting = db.setVoicemailSetting;
export const seedVoicemailSettings = db.seedVoicemailSettings;
export const getAllVoicemailMessages = db.getAllVoicemailMessages;
export const getVoicemailStorageStats = db.getVoicemailStorageStats;
export const pool = db.pool;
